from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm


def generate_pdf_report(candidate, decision):
    file_name = f"{candidate['name']}_ATS_Report.pdf"
    c = canvas.Canvas(file_name, pagesize=A4)

    width, height = A4
    y = height - 2 * cm

    def draw(text):
        nonlocal y
        c.drawString(2 * cm, y, text)
        y -= 14

    # ---------- HEADER ----------
    c.setFont("Helvetica-Bold", 16)
    draw("AI Resume Screening – ATS Report")
    y -= 10

    c.setFont("Helvetica", 11)
    draw(f"Candidate Name: {candidate['name']}")
    draw(f"ATS Score: {candidate['score']}%")
    draw(f"HR Decision: {decision}")
    y -= 10

    # ---------- SKILLS ----------
    c.setFont("Helvetica-Bold", 12)
    draw("Matched Skills:")
    c.setFont("Helvetica", 11)
    for skill in candidate["matched_skills"]:
        draw(f"• {skill}")

    y -= 8
    c.setFont("Helvetica-Bold", 12)
    draw("Missing Skills:")
    c.setFont("Helvetica", 11)
    if candidate["missing_skills"]:
        for skill in candidate["missing_skills"]:
            draw(f"• {skill}")
    else:
        draw("• None")

    y -= 8
    c.setFont("Helvetica-Bold", 12)
    draw("Rejection Reasons:")
    c.setFont("Helvetica", 11)
    for reason in candidate["reasons"]:
        draw(f"• {reason}")

    y -= 8
    c.setFont("Helvetica-Bold", 12)
    draw("Resume Improvement Roadmap:")
    c.setFont("Helvetica", 11)
    for step in candidate["roadmap"]:
        draw(f"• {step}")

    y -= 10
    c.setFont("Helvetica-Oblique", 10)
    draw("Generated by AI Resume Screening System")

    c.save()
    return file_name
